name: Stock Notifier

on:
  schedule:
    # Action Run 1: 09:00 WIB (02:00 UTC), Senin-Jumat
    # Action Run 2: 15:00 WIB (08:00 UTC), Senin-Jumat
    - cron: '0 2,8 * * 1-5'
  workflow_dispatch: # Memungkinkan kita menjalankan ini secara manual jika dibutuhkan

jobs:
  run-notifier:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # Mempercepat instalasi dependencies pada run selanjutnya
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Stock Notifier Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py
