name: Stock Notifier

on:
  schedule:
    # 06:00 WIB Senin-Jumat (Setara dengan 23:00 UTC Minggu-Kamis)
    - cron: '0 23 * * 0-4'
    # 07:00 s/d 18:00 WIB Senin-Jumat (Setara 00:00 s/d 11:00 UTC)
    - cron: '0 0-11 * * 1-5'
  workflow_dispatch: # Memungkinkan kita menjalankan ini secara manual jika dibutuhkan

jobs:
  run-notifier:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # Mempercepat instalasi dependencies pada run selanjutnya
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Stock Notifier Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py
